Register_Project (Field Validation Senarious)

FOR FIRSTNAME FIELD

1]  ALL FIELD IS REQUIRED.
2]  FIRSTNAME, LASTNAME,EMAIL,MOBILENO,PASSWORD IS REQUIRED.
3]  FIRSTNAME, LASTNAME,EMAIL,MOBILENO IS REQUIRED.
4]  FIRSTNAME, LASTNAME,EMAIL IS REQUIRED.
5]  FIRSTNAME, LASTNAME IS REQUIRED.
6]  FIRSTNAME, EMAIL IS REQUIRED
7]  FIRSTNAME, MOBILENO IS REQUIRED.
8]  FIRSTNAME, PASSWORD IS REQUIRED
9]  FIRSTNAME, CONFIRM PASSWORD IS REQUIRED
10] FIRSTNAME IS REQUIRED.
11] FIRSTNAME MUST BE ATLEAST 3 CHARECTER.
12] FIRSTNAME MUST BE LESS THAN 20 CHARCHTER.
13] FIRSTNAME FIELD ACCEPT ONLY ALPHABETS.
==================================================

FOR LASTNAME FIELD

1]  LASTNAME,EMAIL,MOBILENO,PASSWORD, CONFIRM PASSWORD IS REQUIRED.
2]  LASTNAME,EMAIL,MOBILENO, PASSWORD IS REQUIRED.
3]  LASTNAME,EMAIL,MOBILENO IS REQUIRED.
4]  LASTNAME,EMAIL IS REQUIRED.
5]  LASTNAME, MOBILENO IS REQUIRED.
6]  LASTNAME, PASSWORD IS REQUIRED.
7]  LASTNAME, CONFIRM PASSWORD IS REQUIRED.
8]  LASTNAME IS REQUIRED.
9]  LASTNAME MUST BE ATLEAST 3 CHARECTER.
10] LASTNAME MUST BE LESS THAN 20 CHARCHTER.
11] LASTNAME FIELD ACCEPT ONLY ALPHABETS.

==================================================

FOR EMAIL FIELD VALIDATION

1] EMAIL,MOBILENO,PASSWORD, CONFIRM PASSWORD IS REQUIRED.
2] EMAIL,MOBILENO,PASSWORD IS REQUIRED.
3] EMAIL,MOBILENO IS REQUIRED.
3] EMAIL, PASSWORD IS REQUIRED.
4] EMAIL, CONFIRM PASSWORD IS REQUIRED.
5] EMAIL IS REQUIRED.
6] VALID EMAIL 

===================================================

FOR MOBILE NUMBER FIELD VALIDATION

1] MOBILENO,PASSWORD, CONFIRM PASSWORD IS REQUIRED.
2] MOBILENO,PASSWORD IS REQUIRED.
3] MOBILENO, CONFIRM PASSWORD IS REQUIED.
4] MOBILENO, FIRSTNAME, LASTNAME IS REQUIRED.
5] MOBILENO IS REQUIRED.
6] VALID MOBILE NUMBER.
7] INVALID MOBILE NUMBER SENARIOUS
   A] SHOULD NOT ACCEPT 0 TO 6 DIGIT AT 1 PLACE
   B] SHOULD NOT ACCEPT 9 DIGITS MOBILE NUMBER
   C] SHOULD NOT ACCEPT MORE 10 DIGITS MOBILE NUMBER.

=========================================================

FOR PASSWORD FIELD VALIDATION
1] PASSWORD AND CONFIRM PASSWORD FIELD IS REQUIRED
2] PASSWORD IS REQUIRED
3] VALID PASSWORD AND CONFIRM PASSWORD.
   A] ATLEAST ONE DIGIT ----[0-9]
   B] ATLEAST ONE LOWERCASE CHARACTER-----[a-z]
   C] ATLEAST ONE UPPERCASE CHARACTER----[A-Z]
   D] ATLEAST ONE SPECIAL CHARACTER---[*.!@#$%^&(){}[]:;<>,.?\|/+=-]
   E] ATLEAST 8 CHARACTERS IN LENGTH, BUT NOT MORE THAN 32

   REGURAL EXPRESSION ="^(?=.*[0-9])(?=.*[a-z])(?=.*[*.!@#$%^&(){}[]:;<>,.?\|/+=-]).{8,32}$"

   Shailesh@chauhan-----invalid atleast one no is required
   Shailesh123-------------invalid atleast one special character is required
   shailesh@123-------invalid atleast uppercase character is required
   SHAILESH@1234-------invalid atleast lowercase character is required
   Sha@12-------------Password Must Be Atleast 8 character
   Shaishchauhanshaiddchdbbfdhb@12udhasdhasihdd-------------Password Must Be less than 32 character

4] IF PASSWORD AND CONFIRM PASSWORD IS NOT MATCH THAN SHOW ERROR





